### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by LoreBadTime** [X1nto/Custom-Bootanimation-Installer#3]
Since the module load itself after mounting system the bootanimation will not change,instead you could make a terminal command automatized module to change it and reset it to original

**Comment by X1nto** [comment]
As far as I got it from your comment, the module works at first restart but then stops working. This may be due to dummy bootanimation.zip I placed under /system/media. I'll test it and I'll try to fix the issue

**Comment by LoreBadTime** [comment]
Nope,the module never worked to me,if i load the module the first time at the reboot the bootanimation don't change,but as watch the media directory i see that ghe bootanimation is replaced with the new one, trying to reboot to see if was a temporary problem,but it didn't work,I think its a module mounting problem,like the bootanimation its changed only after that the system is started and becaming useless,so i suggest to make a terminal emulator command(like system font changer from repoes) to patch the bootanimation,with a buckup to internal memory(if there is a new file in that directory the OTA are invalideted) and restore it when disabled,another idea could be executing a shell script outside the magisk shell,to only patch without unistall,with a second module that is the restorer

**Comment by X1nto** [comment]
Could you check if you have a bootanimation.zip under /system/media? Some ROMs use different locations for boot animation and that could be a problem.

**Comment by LoreBadTime** [comment]
![Screenshot_2020-02-20-17-33-26-655_eu thedarken sdm](https://user-images.githubusercontent.com/46106812/74956987-2fb33780-5407-11ea-8d2a-7feb97f924b3.jpg)
(I have changed it manually now)

**Comment by X1nto** [comment]
So I checked everything within the module, tested it in 3 of my devices and all work flawlessly. I believe there's either some problem with MiUI or permissions just don't work, make sure to be using my latest installer (v1.0) from Releases tab on GitHub. Could you try injecting my module again and screenshot ring /system/media again? I just want to see if permissions are set correctly (-rw-r--r--)

**Comment by LoreBadTime** [comment]
Permissions are set correctly
![Screenshot_2020-02-22-16-45-37-745_eu thedarken sdm](https://user-images.githubusercontent.com/46106812/75095263-4eded000-5593-11ea-9894-1af629922c66.jpg) but still the bootanimation doesnt load on boot, i have to manually change it,may

**Comment by X1nto** [comment]
Are you using a recovery or Magisk manager to flash it? Also what version of Magisk are you using?

**Comment by LoreBadTime** [comment]
Magisk 20.3 stable

**Comment by X1nto** [comment]
Try with canary build, if that won't work either, blame MemeUI
